apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gcr.io/google-containers/busybox
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"

      #startup probe
      startupProbe:
        exec:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          failureThreshold: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          timeoutSeconds: 5

        liveneessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
          sucessThreshold: 1

        ports:
          - containerPort: 8080
