version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D@4u1985
      MYSQL_USER: orders
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: D@4u1985
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
