version: '3'
services:
  mysql:
    image: mysql:5.7.40
    restart: always
    container_name: mysqlcourse
    environment:
      MYSQL_DATABASE: courses
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@admin
      MYSQL_ROOT_PASSWORD: adminroot
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
